name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12.x
        - run: npm ci
        - run: npm test
        - uses: go-semantic-release/action@v1
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            update-file: package.json
